---
driver_plugin: digitalocean
driver_config:
  flavor_id: 63
  require_chef_omnibus: latest

platforms:
- name: ubuntu-14.10
  run_list:
  - recipe[ubuntu]
  attributes:
    minecraft:
      accept_eula: true
- name: ubuntu-15.04
  run_list:
  - recipe[ubuntu]
  attributes:
    minecraft:
      accept_eula: true
- name: debian-7.0
  provisioner:
    sudo: false
  busser:
    sudo: false
  run_list:
  - recipe[apt]
  attributes:
    minecraft:
      accept_eula: true
- name: debian-6.0
  run_list:
  - recipe[apt]
  attributes:
    minecraft:
      accept_eula: true
- name: centos-6.5
  run_list:
  - recipe[yum-epel]
  attributes:
    minecraft:
      accept_eula: true
- name: centos-7.0
  run_list:
  - recipe[yum-epel]
  attributes:
    minecraft:
      accept_eula: true
suites:
- name: default
  run_list:
  - recipe[minecraft]
  attributes:
- name: spigot
  run_list:
  - recipe[minecraft]
  - recipe[minecraft-test]
  attributes:
    minecraft:
      install_type: "spigot"
      accept_eula: true
