---
driver:
  name: digitalocean
  flavor_id: 63

platforms:
- name: ubuntu-16
  run_list:
  - recipe[ubuntu]
  attributes:
    minecraft:
      accept_eula: true
- name: ubuntu-17
  run_list:
  - recipe[ubuntu]
  attributes:
    minecraft:
      accept_eula: true
- name: debian-8.0
  run_list:
  - recipe[apt]
  attributes:
    minecraft:
      accept_eula: true
- name: debian-9.0
  run_list:
  - recipe[apt]
  attributes:
    minecraft:
      accept_eula: true
- name: centos-6.5
  run_list:
  - recipe[yum-epel]
  attributes:
    minecraft:
      accept_eula: true
- name: centos-7.0
  run_list:
  - recipe[yum-epel]
  attributes:
    minecraft:
      accept_eula: true
suites:
- name: default
  run_list:
  - recipe[minecraft]
  attributes:
